[package]
name = "tmi"
version = "1.0.0"
edition = "2021"
authors = ["Nicholas White"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4"
clap = { version = "4", features = ["derive"] }

